# Generated by Django 6.0.6 on 2026-07-29 11:33

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=contracts.models.next_contract_number, unique=True, verbose_name='Shartnoma №')),
                ('date', models.DateField(verbose_name='Shartnoma sanasi')),
                ('collateral_type', models.CharField(choices=[('zargarlik', 'Zargarlik buyumlari garovi'), ('transport', 'Transport vositasi garovi'), ('kafillik', 'Ish haqi kafilligi')], max_length=12, verbose_name="Ta'minot turi")),
                ('borrower_fio', models.CharField(max_length=200, verbose_name='Qarz oluvchi F.I.Sh. (kirillda)')),
                ('passport_region', models.CharField(blank=True, help_text='Masalan: Бухоро вилояти', max_length=100, verbose_name='Hujjat berilgan viloyat')),
                ('passport_org', models.CharField(help_text='Masalan: 61013-сонли', max_length=50, verbose_name="IIV bo'lim raqami")),
                ('passport_date', models.DateField(verbose_name='Hujjat berilgan sana')),
                ('passport_number', models.CharField(help_text='Masalan: АE№2437494', max_length=30, verbose_name='Hujjat seriya-raqami')),
                ('borrower_address', models.CharField(max_length=300, verbose_name='Manzil (kirillda)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name="Kredit summasi (so'm)")),
                ('term_months', models.PositiveIntegerField(default=12, verbose_name='Muddat (oy)')),
                ('interest_rate', models.PositiveIntegerField(default=60, verbose_name='Yillik foiz (%)')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('garov_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Garov shartnomasi №')),
                ('garov_value', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name="Garov bahosi (so'm)")),
                ('status', models.CharField(choices=[('active', 'Faol'), ('pending_delete', "O'chirish so'ralgan")], default='active', max_length=15, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritgan')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.PositiveIntegerField(verbose_name='Shartnoma №')),
                ('contract_info', models.CharField(blank=True, max_length=300, verbose_name='Shartnoma haqida')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Sabab')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="So'ralgan vaqt")),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rilgan vaqt")),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlashi kerak')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_requests', to='contracts.contract')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to=settings.AUTH_USER_MODEL, verbose_name="So'ragan ishchi")),
            ],
            options={
                'verbose_name': "O'chirish so'rovi",
                'verbose_name_plural': "O'chirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuarantorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='Kafil F.I.Sh. (kirillda)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name="Kafillik summasi (so'm)")),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Kafil',
                'verbose_name_plural': 'Kafillar',
            },
        ),
        migrations.CreateModel(
            name='JewelryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi (kirillda)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni (dona)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Og'irligi (gr)")),
                ('proba', models.CharField(default='585', max_length=10, verbose_name='Probasi')),
                ('value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name="Summasi (so'm)")),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_items', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Zargarlik buyumi',
                'verbose_name_plural': 'Zargarlik buyumlari',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(help_text='Masalan: “Express Alligator Bukhara” МЧЖ yoki F.I.Sh.', max_length=250, verbose_name="Egasi (garovga qo'yuvchi)")),
                ('owner_head', models.CharField(blank=True, max_length=200, verbose_name="Tashkilot rahbari (bo'lsa)")),
                ('state_number', models.CharField(max_length=20, verbose_name='Davlat raqami')),
                ('model', models.CharField(max_length=100, verbose_name='Rusumi')),
                ('color', models.CharField(max_length=50, verbose_name='Rangi')),
                ('body_number', models.CharField(blank=True, default='-', max_length=50, verbose_name='Kuzov raqami')),
                ('chassis_number', models.CharField(blank=True, default='-', max_length=50, verbose_name='Shassi raqami')),
                ('engine_number', models.CharField(blank=True, default='-', max_length=50, verbose_name='Dvigatel raqami')),
                ('year', models.CharField(max_length=10, verbose_name='Ishlab chiqarilgan yili')),
                ('techpassport', models.CharField(help_text='Masalan: AAG 0949387 / 14.02.2023', max_length=100, verbose_name='Texpasport raqami va sanasi')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Transport vositasi',
                'verbose_name_plural': 'Transport vositalari',
            },
        ),
    ]
