# Generated by Django 6.0.6 on 2026-07-29 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_passport_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='passport_org',
            field=models.CharField(help_text='Faqat raqam. Masalan: 61013', max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', 'Faqat raqam kiriting.')], verbose_name="IIV bo'lim raqami"),
        ),
    ]
