# Generated by Django 6.0.6 on 2026-07-30 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_passport_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('kim_nomi', models.CharField(max_length=150, verbose_name='Kim (nusxa)')),
                ('kim_roli', models.CharField(blank=True, max_length=10, verbose_name='Roli')),
                ('amal', models.CharField(choices=[('shartnoma_yaratdi', 'Shartnoma yaratdi'), ('shartnoma_ozgartirdi', 'Shartnomani o‘zgartirdi'), ('shartnoma_ochirdi', 'Shartnomani o‘chirdi'), ('sorov_yubordi', 'O‘chirish so‘rovi yubordi'), ('sorov_tasdiqladi', 'O‘chirish so‘rovini tasdiqladi'), ('sorov_rad_etdi', 'O‘chirish so‘rovini rad etdi'), ('ishchi_qoshdi', 'Ishchi qo‘shdi'), ('ishchi_boshatdi', 'Ishchini bo‘shatdi'), ('ishchi_ochirdi', 'Ishchini o‘chirdi'), ('parol_ozgartirdi', 'Parolni o‘zgartirdi'), ('shablon_ozgartirdi', 'Shablonni o‘zgartirdi'), ('hujjat_oldi', 'Hujjatni yuklab oldi')], db_index=True, max_length=25, verbose_name='Amal')),
                ('obyekt', models.CharField(blank=True, max_length=200, verbose_name='Nimaga')),
                ('izoh', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amallar', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
            ],
            options={
                'verbose_name': 'Amal',
                'verbose_name_plural': 'Amallar tarixi',
                'ordering': ['-vaqt'],
            },
        ),
    ]
