# Generated by Django 6.0.6 on 2026-08-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_amal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='borrower_phone',
            field=models.CharField(blank=True, help_text='Masalan: 91 415-00-87', max_length=25, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name="Oylik daromad (so'm)"),
        ),
    ]
