# Generated by Django 6.0.6 on 2026-08-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_borrower_phone_contract_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='garov_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Garov shartnomasi № (eskirgan)'),
        ),
    ]
