# Generated by Django 6.0.6 on 2026-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_garov_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='borrower_phone',
            field=models.CharField(blank=True, help_text='Masalan: 12 345-67-89', max_length=25, verbose_name='Telefon raqami'),
        ),
    ]
