# Generated by Django 6.0.6 on 2026-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_borrower_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='borrower_phone2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefon raqami 2'),
        ),
        migrations.AddField(
            model_name='contract',
            name='borrower_phone3',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefon raqami 3'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='borrower_phone',
            field=models.CharField(blank=True, help_text='Masalan: 12 345-67-89', max_length=25, verbose_name='Telefon raqami 1'),
        ),
    ]
