# Generated by Django 6.0.6 on 2026-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_borrower_phone2_contract_borrower_phone3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='borrower_workplace',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ish joyi va manzili (kirillda)'),
        ),
    ]
