# Generated by Django 6.0.6 on 2026-08-14 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_borrower_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='passport_type',
            field=models.CharField(choices=[('id_karta', 'ID karta'), ('passport', 'Biometrik pasport (yashil)')], default='id_karta', max_length=10, verbose_name='Hujjat turi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil (kirillda)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_fio',
            field=models.CharField(blank=True, max_length=200, verbose_name="Garovga qo'yuvchi F.I.Sh. (kirillda)"),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_other',
            field=models.BooleanField(default=False, verbose_name="Garovga qo'yuvchi boshqa shaxs"),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hujjat berilgan sana'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_passport_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Hujjat seriya-raqami'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_passport_org',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^\\d*$', 'Faqat raqam kiriting.')], verbose_name="IIV bo'lim raqami"),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_passport_region',
            field=models.CharField(blank=True, choices=[('Андижон вилояти', 'Андижон вилояти'), ('Бухоро вилояти', 'Бухоро вилояти'), ('Жиззах вилояти', 'Жиззах вилояти'), ('Навоий вилояти', 'Навоий вилояти'), ('Наманган вилояти', 'Наманган вилояти'), ('Самарқанд вилояти', 'Самарқанд вилояти'), ('Сирдарё вилояти', 'Сирдарё вилояти'), ('Сурхондарё вилояти', 'Сурхондарё вилояти'), ('Тошкент вилояти', 'Тошкент вилояти'), ('Фарғона вилояти', 'Фарғона вилояти'), ('Хоразм вилояти', 'Хоразм вилояти'), ('Қашқадарё вилояти', 'Қашқадарё вилояти'), ('Тошкент шаҳри', 'Тошкент шаҳри'), ('Қорақалпоғистон Республикаси', 'Қорақалпоғистон Республикаси')], max_length=100, verbose_name='Hujjat berilgan viloyat'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_passport_type',
            field=models.CharField(blank=True, choices=[('id_karta', 'ID karta'), ('passport', 'Biometrik pasport (yashil)')], max_length=10, verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='garov_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Garov shartnomasi №'),
        ),
    ]
