# Generated by Django 6.0.6 on 2026-08-14 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_passport_type_contract_pledgor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='passport_org',
            field=models.CharField(blank=True, help_text='Faqat raqam. Masalan: 61013', max_length=50, validators=[django.core.validators.RegexValidator('^\\d*$', 'Faqat raqam kiriting.')], verbose_name="IIV bo'lim raqami"),
        ),
    ]
