# Generated by Django 6.0.6 on 2026-08-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contract_passport_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name="Birinchi to'lov sanasi"),
        ),
    ]
