# Generated by Django 6.0.6 on 2026-08-15 09:06

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_payment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='garov_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Garov shartnomasi № (eskirgan)'),
        ),
        migrations.CreateModel(
            name='GarovRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to=contracts.models.garov_rasm_yoli, verbose_name='Surat')),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garov_rasmlari', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Garov surati',
                'verbose_name_plural': 'Garov suratlari',
                'ordering': ['id'],
            },
        ),
    ]
