# Generated by Django 6.0.6 on 2026-08-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_contract_garov_number_garovrasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Grafik boshlanish sanasi'),
        ),
    ]
