# Generated by Django 6.0.6 on 2026-08-17 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_contract_payment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='passport_district',
            field=models.CharField(blank=True, help_text='Masalan: Когон тумани', max_length=100, validators=[django.core.validators.RegexValidator("^[Ѐ-ӿ\\s\\'’\\-]*$", 'Tuman nomini kirillcha yozing. Masalan: Когон тумани')], verbose_name='Tuman (kirillcha)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pledgor_passport_district',
            field=models.CharField(blank=True, help_text='Masalan: Когон тумани', max_length=100, validators=[django.core.validators.RegexValidator("^[Ѐ-ӿ\\s\\'’\\-]*$", 'Tuman nomini kirillcha yozing. Masalan: Когон тумани')], verbose_name='Tuman (kirillcha)'),
        ),
    ]
