# Generated by Django 6.0.6 on 2026-08-17 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_contract_passport_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='passport_district',
            field=models.CharField(blank=True, help_text='Masalan: Когон тумани', max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zЀ-ӿ\\s\\'’\\-]*$", 'Tuman nomini harflar bilan yozing (raqam va belgilarsiz).')], verbose_name='Tuman (kirillcha)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pledgor_passport_district',
            field=models.CharField(blank=True, help_text='Masalan: Когон тумани', max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zЀ-ӿ\\s\\'’\\-]*$", 'Tuman nomini harflar bilan yozing (raqam va belgilarsiz).')], verbose_name='Tuman (kirillcha)'),
        ),
    ]
