# Generated by Django 6.0.6 on 2026-08-25 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_contract_passport_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='egasi_turi',
            field=models.CharField(choices=[('oz', 'Qarz oluvchiniki'), ('shaxs', 'Boshqa jismoniy shaxs'), ('tashkilot', 'Tashkilot')], default='oz', max_length=10, verbose_name='Mashina egasi'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Egasining manzili (kirillda)'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hujjat berilgan sana'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_passport_district',
            field=models.CharField(blank=True, help_text='Masalan: Когон тумани', max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zЀ-ӿ\\s\\'’\\-]*$", 'Tuman nomini harflar bilan yozing (raqam va belgilarsiz).')], verbose_name='Tuman (kirillcha)'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_passport_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Hujjat seriya-raqami'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_passport_org',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^\\d*$', 'Faqat raqam kiriting.')], verbose_name="IIV bo'lim raqami"),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_passport_region',
            field=models.CharField(blank=True, choices=[('Андижон вилояти', 'Андижон вилояти'), ('Бухоро вилояти', 'Бухоро вилояти'), ('Жиззах вилояти', 'Жиззах вилояти'), ('Навоий вилояти', 'Навоий вилояти'), ('Наманган вилояти', 'Наманган вилояти'), ('Самарқанд вилояти', 'Самарқанд вилояти'), ('Сирдарё вилояти', 'Сирдарё вилояти'), ('Сурхондарё вилояти', 'Сурхондарё вилояти'), ('Тошкент вилояти', 'Тошкент вилояти'), ('Фарғона вилояти', 'Фарғона вилояти'), ('Хоразм вилояти', 'Хоразм вилояти'), ('Қашқадарё вилояти', 'Қашқадарё вилояти'), ('Тошкент шаҳри', 'Тошкент шаҳри'), ('Қорақалпоғистон Республикаси', 'Қорақалпоғистон Республикаси')], max_length=100, verbose_name='Hujjat berilgan viloyat'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='owner_passport_type',
            field=models.CharField(blank=True, choices=[('id_karta', 'ID karta'), ('passport', 'Biometrik pasport (yashil)')], max_length=10, verbose_name='Egasining hujjati'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='owner',
            field=models.CharField(blank=True, help_text='Masalan: “Express Alligator Bukhara” МЧЖ yoki F.I.Sh.', max_length=250, verbose_name="Egasi (garovga qo'yuvchi)"),
        ),
    ]
