# Generated by Django 6.0.6 on 2026-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_egasi_turini_aniqlash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='egasi_turi',
            field=models.CharField(choices=[('oz', 'Qarz oluvchiniki'), ('shaxs', 'Boshqa (jismoniy shaxs)'), ('tashkilot', 'Boshqa (tashkilot)')], default='oz', max_length=10, verbose_name='Mashina egasi'),
        ),
    ]
