# Generated by Django 6.0.6 on 2026-08-25 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_alter_vehicleinfo_egasi_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='borrower_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefon raqami 1'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport_district',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zЀ-ӿ\\s\\'’\\-]*$", 'Tuman nomini harflar bilan yozing (raqam va belgilarsiz).')], verbose_name='Tuman (kirillcha)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport_number',
            field=models.CharField(max_length=30, verbose_name='Hujjat seriya-raqami'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport_org',
            field=models.CharField(blank=True, help_text='Faqat raqam.', max_length=50, validators=[django.core.validators.RegexValidator('^\\d*$', 'Faqat raqam kiriting.')], verbose_name="IIV bo'lim raqami"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pledgor_passport_district',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zЀ-ӿ\\s\\'’\\-]*$", 'Tuman nomini harflar bilan yozing (raqam va belgilarsiz).')], verbose_name='Tuman (kirillcha)'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='owner',
            field=models.CharField(blank=True, max_length=250, verbose_name="Egasi (garovga qo'yuvchi)"),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='owner_passport_district',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zЀ-ӿ\\s\\'’\\-]*$", 'Tuman nomini harflar bilan yozing (raqam va belgilarsiz).')], verbose_name='Tuman (kirillcha)'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='techpassport',
            field=models.CharField(max_length=100, verbose_name='Texpasport raqami va sanasi'),
        ),
    ]
