# Generated by Django 6.1.1 on 2026-09-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_alter_contract_borrower_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalit', models.CharField(help_text='Hujjat raqami ajratgichlarsiz: AE5862145', max_length=30, unique=True, verbose_name='Qidiruv kaliti')),
                ('fio', models.CharField(max_length=200, verbose_name='F.I.Sh. (kirillda)')),
                ('passport_type', models.CharField(choices=[('id_karta', 'ID karta'), ('passport', 'Biometrik pasport (yashil)')], default='id_karta', max_length=10, verbose_name='Hujjat turi')),
                ('passport_region', models.CharField(blank=True, choices=[('Андижон вилояти', 'Андижон вилояти'), ('Бухоро вилояти', 'Бухоро вилояти'), ('Жиззах вилояти', 'Жиззах вилояти'), ('Навоий вилояти', 'Навоий вилояти'), ('Наманган вилояти', 'Наманган вилояти'), ('Самарқанд вилояти', 'Самарқанд вилояти'), ('Сирдарё вилояти', 'Сирдарё вилояти'), ('Сурхондарё вилояти', 'Сурхондарё вилояти'), ('Тошкент вилояти', 'Тошкент вилояти'), ('Фарғона вилояти', 'Фарғона вилояти'), ('Хоразм вилояти', 'Хоразм вилояти'), ('Қашқадарё вилояти', 'Қашқадарё вилояти'), ('Тошкент шаҳри', 'Тошкент шаҳри'), ('Қорақалпоғистон Республикаси', 'Қорақалпоғистон Республикаси')], max_length=100, verbose_name='Hujjat berilgan viloyat')),
                ('passport_org', models.CharField(blank=True, max_length=50, verbose_name="IIV bo'lim raqami")),
                ('passport_district', models.CharField(blank=True, max_length=100, verbose_name='Tuman (kirillcha)')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Hujjat berilgan sana')),
                ('passport_number', models.CharField(max_length=30, verbose_name='Hujjat seriya-raqami')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil (kirillda)')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon raqami 1')),
                ('phone2', models.CharField(blank=True, max_length=25, verbose_name='Telefon raqami 2')),
                ('phone3', models.CharField(blank=True, max_length=25, verbose_name='Telefon raqami 3')),
                ('workplace', models.CharField(blank=True, max_length=300, verbose_name='Ish joyi va manzili')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name="Oylik daromad (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Bazaga qo'shilgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['fio'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shartnomalar', to='contracts.mijoz', verbose_name='Mijoz'),
        ),
    ]
