# Generated by Django 6.0.6 on 2026-07-29 12:35

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boshliq',
            fields=[
            ],
            options={
                'verbose_name': 'Boshliq',
                'verbose_name_plural': 'Boshliqlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.BoshliqManager()),
            ],
        ),
    ]
