# Generated by Django 6.0.6 on 2026-07-30 11:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_boshliq'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.LombardUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_template',
            field=models.BooleanField(default=False, help_text='Belgilansa, bu boshliq Word shablonlarini almashtira oladi.', verbose_name='Shablonni o‘zgartirish vakolati'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('boshliq', 'Boshliq'), ('ishchi', 'Ishchi'), ('admin', 'Faqat admin panel (saytga kirmaydi)')], default='ishchi', max_length=10, verbose_name='Rol'),
        ),
    ]
